---
title: "DEVELOPING DATA PRODUCT WEEK-3 ASSIGNMENT"
author: "Vasudha Singh"
date: "December 26, 2018"
output:
  ioslides_presentation: default
  slidy_presentation: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(plotly)
library(httpuv)
library(mime)
library(bindrcpp)
```

## INTRODUCTION

- Creating a web page presentation using R Markdown that features a plot created with Plotly.

- Hosted my webpage on RPubs. 

- we have taken the **Emission data of Baltimore city** dataset to make plot.


##PLOT SHOWING THE RELATION BETWEEN THE EMISSION PER YEAR IN THE BALTIMORE CITY

```{r, echo=FALSE}

##Download and Unziped the file 
url<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip"
datafile1<-"datafile1.zip"
if(!file.exists(datafile1)){download.file(url, destfile=datafile1, method="auto"); unzip(datafile1, exdir=".")}

##Reading the dataset
NEI <-readRDS("summarySCC_PM25.rds")
SCC<-readRDS("Source_Classification_Code.rds")

##Finding subset of NEI for Baltimore City (Maryland, fips="24510")
baltimore<- subset(NEI,NEI$fips=="24510")

## Finding the Total emission of Baltimore City per year and Type
baltimore_total_emission <- aggregate(baltimore$Emissions,by=list(baltimore$type, baltimore$year),
                                      FUN=sum)
colnames(baltimore_total_emission)<- c("type","year","Emission")


plot_ly(data=baltimore_total_emission, x= ~year, y= ~Emission, color= ~type, type="bar")%>%
  layout(title="Total emission per year", xaxis=list(title="Year"), yaxis=list(title="Emission"))

``` 


